import React,{useState} from 'react';
import {Alert,KeyboardAvoidingView,Platform,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {C,money,suggestions} from './config';
import {Button,Card,ChallengeCard} from './ui';
export function Home({challenges,totalSaved,totalTarget,open,discover}){return <ScrollView contentContainerStyle={{padding:16,paddingBottom:118,gap:16}}><Card style={{backgroundColor:C.nav,borderColor:C.nav,padding:22}}><Text style={{color:'#BFD0C5',fontSize:13,fontWeight:'700'}}>GESAMT GESPART</Text><Text selectable style={{color:'#FFF',fontSize:40,fontWeight:'900',letterSpacing:-1.4,fontVariant:['tabular-nums']}}>{money(totalSaved)}</Text><View style={{flexDirection:'row',gap:10}}><Stat label="Zielsumme" value={money(totalTarget)}/><Stat label="Challenges" value={String(challenges.length)}/></View></Card><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={h}>Deine Challenges</Text><Text onPress={discover} style={{color:C.green,fontWeight:'800'}}>Entdecken</Text></View>{challenges.length?challenges.slice(0,4).map(c=><ChallengeCard key={c.id} challenge={c} onPress={()=>open(c.id)}/>):<Card><Text style={{fontSize:34}}>🌿</Text><Text style={h}>Starte mit einem kleinen Ziel</Text><Text style={p}>Wähle eine vorgeschlagene Challenge oder erstelle dein eigenes Sparziel.</Text><Button title="Challenges ansehen" onPress={discover}/></Card>}<Card style={{backgroundColor:'#FFF8EA'}}><Text style={{color:C.gold,fontWeight:'800'}}>SPAR-TIPP</Text><Text style={h}>Kleine Beträge sichtbar machen.</Text><Text style={{color:'#7E6A45',lineHeight:20}}>1 €, 2 € oder 5 € wirken klein – regelmäßige Schritte bringen dich ans Ziel.</Text></Card></ScrollView>}
function Stat({label,value}){return <View style={{flex:1,padding:13,borderRadius:16,backgroundColor:'rgba(255,255,255,.08)'}}><Text style={{color:'#BFD0C5',fontSize:11}}>{label}</Text><Text selectable style={{color:'#FFF',fontSize:16,fontWeight:'800'}}>{value}</Text></View>}
export function Challenges({challenges,activate,open}){const active=new Set(challenges.map(c=>c.templateId).filter(Boolean));return <ScrollView contentContainerStyle={{padding:16,paddingBottom:118,gap:14}}>{challenges.length?<><Text style={h}>Aktiv</Text>{challenges.map(c=><ChallengeCard key={c.id} challenge={c} onPress={()=>open(c.id)}/>)}</>:null}<Text style={[h,{marginTop:4}]}>Vorgeschlagen</Text>{suggestions.map(s=><Card key={s.id}><View style={{flexDirection:'row',gap:12}}><Text style={{fontSize:30}}>{s.emoji}</Text><View style={{flex:1,gap:4}}><Text style={{color:C.ink,fontSize:17,fontWeight:'800'}}>{s.title}</Text><Text style={p}>{s.description}</Text></View></View><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:C.green,fontWeight:'800'}}>{money(s.target)}</Text><Text style={{color:C.muted}}>{s.days} Tage</Text></View><Button title={active.has(s.id)?'Bereits aktiv':'Challenge starten'} disabled={active.has(s.id)} onPress={()=>activate(s)}/></Card>)}</ScrollView>}
export function Create({create,done}){const[title,setTitle]=useState('');const[target,setTarget]=useState('');const[description,setDescription]=useState('');const[emoji,setEmoji]=useState('🎯');const[days,setDays]=useState(90);const n=Number(target.replace(',','.'));const valid=title.trim().length>=2&&Number.isFinite(n)&&n>0;const input={minHeight:52,borderRadius:16,borderWidth:1,borderColor:C.line,backgroundColor:'#FFF',paddingHorizontal:14,color:C.ink,fontSize:16};return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={58}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:16,paddingBottom:118,gap:14}}><Card><Text style={h}>Dein Sparziel</Text><TextInput value={title} onChangeText={setTitle} placeholder="z. B. Neues Handy" placeholderTextColor="#9AA79F" style={input}/><TextInput value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder="Zielbetrag in €" placeholderTextColor="#9AA79F" style={input}/><TextInput value={description} onChangeText={setDescription} multiline placeholder="Beschreibung (optional)" placeholderTextColor="#9AA79F" style={[input,{minHeight:88,paddingTop:14,textAlignVertical:'top'}]}/></Card><Card><Text style={h}>Zeitraum</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[30,90,180,365].map(v=><Chip key={v} active={days===v} onPress={()=>setDays(v)} label={v===365?'1 Jahr':`${v} Tage`}/>)}</View></Card><Card><Text style={h}>Symbol</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:9}}>{['🎯','💚','🏖️','🚗','🏠','📱','🎁','🛟'].map(v=><Pressable key={v} onPress={()=>setEmoji(v)} style={{width:48,height:48,borderRadius:15,backgroundColor:emoji===v?C.greenSoft:'#F2F5F2',alignItems:'center',justifyContent:'center',borderWidth:emoji===v?2:0,borderColor:C.green}}><Text style={{fontSize:24}}>{v}</Text></Pressable>)}</View></Card><Button disabled={!valid} title="Challenge erstellen" onPress={async()=>{await create({title:title.trim(),description:description.trim()||'Mein persönliches Sparziel.',target:n,days,emoji});setTitle('');setTarget('');setDescription('');done()}}/></ScrollView></KeyboardAvoidingView>}
function Chip({active,onPress,label}){return <Pressable onPress={onPress} style={{paddingHorizontal:13,paddingVertical:9,borderRadius:99,backgroundColor:active?C.green:'#EEF2EF'}}><Text style={{color:active?'#FFF':C.muted,fontWeight:'800'}}>{label}</Text></Pressable>}
export function More({count,reset}){return <ScrollView contentContainerStyle={{padding:16,paddingBottom:118,gap:14}}><Card><Text style={{fontSize:30}}>🔒</Text><Text style={h}>Lokal & privat</Text><Text style={p}>Zielora speichert deine Spar-Challenges nur lokal auf deinem iPhone. Kein Konto und keine Bankverbindung.</Text></Card><Card><Text style={h}>Gespeicherte Daten</Text><Text style={p}>{count} Challenge{count===1?'':'s'} auf diesem Gerät.</Text><Button danger title="Alle Daten löschen" onPress={reset}/></Card><Text style={{textAlign:'center',color:'#98A49D',fontSize:12}}>Zielora 1.0 · iPhone Edition</Text></ScrollView>}
export const requestReset=(action)=>Alert.alert('Alle Daten löschen?','Alle Challenges und Einzahlungen werden entfernt.',[{text:'Abbrechen',style:'cancel'},{text:'Löschen',style:'destructive',onPress:action}]);
const h={color:C.ink,fontSize:19,fontWeight:'800'};const p={color:C.muted,lineHeight:20};
